export const SET_TRACK_LOADING = 'SET_TRACK_LOADING'
export const SET_SELECTED_TRACK = 'SET_SELECTED_TRACK'
export const SET_TRACK_LIST = 'SET_TRACK_LIST'
export const ADD_TRACK_TO_LIST = 'ADD_TRACK_TO_LIST'
